name: Lint and Commit
on:
  push:
    branches:
      - master
jobs:
  lint_and_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Linters
        run: | 
          pip install ruff
          pip install isort
          pip install black
          npm install -g prettier 

      - name: Run Linters
        run: |
          isort .
          black .
          ruff check --fix
          npx prettier --write 'website/**/*.{css,scss}'          

      - name: Commit changes to GitHub
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Automated code formatting applied.'
